/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT FBIOS.cdb */

/*  Include Header Files  */
#include <std.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far SWI_Obj KNL_swi;
extern far TSK_Obj TSK_idle;
extern far TSK_Obj TSK0;
extern far TSK_Obj TSK1;
extern far TSK_Obj TSK2;
extern far LOG_Obj LOG_system;
extern far SEM_Obj SEM0;


#ifdef __cplusplus
}
#endif /* extern "C" */
